import { dropdown } from '../types/TaskTypes'; // Adjust path if needed

export const taskDropdownData: dropdown[] = [
  {
    taskid: 'T001',
    taskName: 'Clean Coffee Station',
    createdBy: 'John Manager',
    status: 'Active',
    value: 'High',
    completionValidation: 'Supervisor',
    area: 'Beverage Zone',
    frequency: 'Daily',
    startingShift: 'Morning',
  },
  {
    taskid: 'T002',
    taskName: 'Stock Cigarette Display',
    createdBy: 'Alice Supervisor',
    status: 'Ended',
    value: 'Normal',
    area: 'Tobacco Section',
    frequency: 'Daily',
  },
  {
    taskid: 'T003',
    taskName: 'Mop Floor - Aisle 3',
    createdBy: 'Mike TeamLead',
    status: 'Ended',
    value: 'High',
    completionValidation: 'Camera',
    area: 'Aisle 3',
    frequency: 'Weekly',
    startingShift: 'Night',
  },
  {
    taskid: 'T004',
    taskName: 'Replenish Bottled Water',
    createdBy: 'Sarah Admin',
    status: 'Active',
    value: 'Normal',
    area: 'Cooler Area',
    frequency: 'EveryShift',
  },
  {
    taskid: 'T005',
    taskName: 'Check Fire Extinguisher Pressure',
    createdBy: 'Bob Safety',
    status: 'Ended',
    value: 'High',
    area: 'All Sections',
    frequency: 'Weekly',
    completionValidation: 'Safety Officer',
  },
];
